Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -73,18 +73,6 @@ jobs:
           name: frontend-coverage
           path: front/coverage/bobapp/
 
-      - name: Check JaCoCo XML (Java)
-        run: |
-          echo "== Checking JaCoCo report =="
-          ls -R back/target/site/jacoco || echo "No JaCoCo directory"
-          cat back/target/site/jacoco/jacoco.xml | head -20 || echo "jacoco.xml missing"
-
-      - name: Check LCOV (Angular)
-        run: |
-          echo "== Checking LCOV report =="
-          ls -R front/coverage || echo "No coverage directory"
-          cat front/coverage/*/lcov.info | head -20 || echo "lcov.info missing"     
-
   sonarqube:
     name: SonarCloud Analysis
     runs-on: ubuntu-latest
@@ -95,6 +83,18 @@ jobs:
         with:
           fetch-depth: 0
 
+      - name: Download backend coverage
+        uses: actions/download-artifact@v4
+        with:
+          name: backend-coverage
+          path: back/target/site/jacoco
+
+      - name: Download frontend coverage
+        uses: actions/download-artifact@v4
+        with:
+          name: frontend-coverage
+          path: front/coverage/bobapp
+
       - name: Set up Java
         uses: actions/setup-java@v4
         with:
@@ -104,6 +104,18 @@ jobs:
       - name: Build backend (required for sonar.java.binaries)
         working-directory: back
         run: mvn -B clean compile
+
+      - name: Check JaCoCo XML
+        run: |
+          echo "== Checking JaCoCo XML report =="
+          ls -R back/target/site/jacoco || echo "No JaCoCo directory"
+          cat back/target/site/jacoco/jacoco.xml | head -20 || echo "jacoco.xml missing"
+
+      - name: Check LCOV
+        run: |
+          echo "== Checking LCOV report =="
+          ls -R front/coverage || echo "No coverage directory"
+          cat front/coverage/*/lcov.info | head -20 || echo "lcov.info missing"
 
       - name: SonarCloud Scan
         uses: SonarSource/sonarcloud-github-action@v2
@@ -120,6 +132,8 @@ jobs:
             -Dsonar.javascript.lcov.reportPaths=front/coverage/*/lcov.info
             -Dsonar.coverage.jacoco.xmlReportPaths=back/target/site/jacoco/jacoco.xml
             -Dsonar.java.binaries=back/target/classes
+            -Dsonar.verbose=true
+
   docker:
     name: Build & Push Docker Images
     runs-on: ubuntu-latest
@@ -153,4 +167,3 @@ jobs:
           tags: |
             ${{ secrets.DOCKER_USERNAME }}/back-app:latest
             ${{ secrets.DOCKER_USERNAME }}/back-app:${{ github.sha }}
-
